#!/usr/bin/env bash

NET_NAME="postgres-ccdb"
DNS_IP="10.0.0.72"
POSTGRES_PORT=5432
LOCAL_POSTGRES_PORT=5432
POSTGRES_USER="ccdb"
POSTGRES_PASSWORD="ccdb"
CCDB_SERVICE_NAME=ccdb-postgres
CCDB_DOCKER_IMAGE_NAME=ccdb-postgres
CCDB_DOCKER_VOLUME=ccdb-postgres-volume
